### ISSUE TITLE
Support for commonjs output

### ISSUE THREAD

**Issue by chardos** [KnisterPeter/react-to-typescript-definitions#667]
First off, thanks for the awesome module. The output looks great.

Currently, I am trying to compile flow definitions from the definitions created by this module, however that library doesn't understand es6 modules (https://github.com/joarwilk/flowgen). Would love for this library to be able to support commonjs output, otherwise, we will have to run babel on the output to transpile it.

**Comment by KnisterPeter** [comment]
@chardos I think I don't get the exact point of your request. The output are just typescript definition files for react components written with prop-types. The definitions are es6 style and I understand that you might need commonjs output. But I think babel would not help here, since babel could not understand definition files.
I would think of a new commandline flag which enables commonjs output. A new code generator for this would be the right path.

Any help would be welcome.
